name: forklift

services:
  back-end:
    build: ./back-end
    container_name: api-forklift
    restart: always
    ports:
      - 3131:3131
    env_file:
      - back-end/.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql-forklift:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - postgresql-forklift
    networks:
      - forklift-network
    volumes:
      - api_forklift_uploads:/usr/src/app/uploads

  front-end:
    build:
      context: ./front-end
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: forklift-front-end
    restart: always
    ports:
      - ${FRONTEND_PORT}:80
    networks:
      - forklift-network
    depends_on:
      - back-end

  postgresql-forklift:
    image: postgres:16
    container_name: postgresql-forklift
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - forklift-network
    volumes:
      - postgres_data_forklift:/var/lib/postgresql/data

volumes:
  postgres_data_forklift:
  api_forklift_uploads:

networks:
  forklift-network:
    name: forklift-network
