name: forklift

services:
  back-end:
    build:
      context: ./back-end
    container_name: forklift-back-end
    restart: always
    ports:
      - ${API_PORT}:3131
    env_file:
      - ./back-end/.env
    depends_on:
      - postgresql-forklift
    networks:
      - forklift-network
    volumes:
      - api_forklift_uploads:/usr/src/app/uploads

  postgresql-forklift:
    image: postgres:16
    container_name: postgresql-forklift
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - forklift-network
    volumes:
      - postgres_data_forklift:/var/lib/postgresql/data

  front-end:
    build:
      context: ./front-end
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: forklift-front-end
    restart: always
    ports:
      - ${FRONTEND_PORT}:5173
    networks:
      - forklift-network
    volumes:
      - ./front-end:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - back-end

volumes:
  postgres_data_forklift:
  api_forklift_uploads:

networks:
  forklift-network:
    name: forklift-network
