name: forklift-back-end

services:
  api-forklift:
    build: .
    container_name: api-forklift
    restart: always
    ports:
      - 3131:3131
    env_file:
      - .env
    depends_on:
      - postgresql-forklift
    networks:
      - forklift-network
    volumes:
      - api_forklift_uploads:/usr/src/app/uploads

  postgresql-forklift:
    image: postgres:16
    container_name: postgresql-forklift
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
    - forklift-network
    volumes:
      - postgres_data_forklift:/var/lib/postgresql/data

volumes:
  postgres_data_forklift:
  api_forklift_uploads:

networks:
  forklift-network:
    name: forklift-network
